---

- name: Ensure the webserver conf files are copied.
  template: src=temp_vhost.conf dest=/etc/apache2/sites-available/{{sub_domain}}-deploy.conf owner=root group=root mode=0644  
  notify: restart apache2
 
- name: Ensure the webserver conf is enabled.
  file: src=/etc/apache2/sites-available/{{sub_domain}}-deploy.conf dest=/etc/apache2/sites-enabled/{{sub_domain}}.conf owner=root group=root state=link
  notify: restart apache2

- name: Ensure Apache2 is started and enabled.
  service: name=apache2 state=started enabled=yes
